name: Business Web PR Preview

on:
  pull_request: {}

jobs:
  deploy_business_web:
    type: deploy
    name: Deploy Business Web Preview
    environment: preview

  comment:
    needs: [deploy_business_web]
    type: github-comment
